version: "3"

volumes:
  mariadb-data:

services:
  mariadb:
    image: mariadb:10.5
    ports: 
      - 33061:3306
    environment:
      - MYSQL_DATABASE=dummydb
      - MYSQL_ROOT_PASSWORD=mariadbpw
      - MYSQL_ALLOW_EMPTY_PASSWORD=YES
    volumes:
      - mariadb-data:/var/lib/mysql
